### PR TITLE
Update to polymer v2 dependencies, fix missing icon property

### PR DESCRIPTION
**Pull request by RoXuS**
For sur @MeTaNoV.

Hello, some little changes on your component.

Thx !

### CODE REVIEW

**Comment by GeoloeG-IsT** [comment]
Merci Julien (@RoXuS)

**Comment by fxedel** [comment]
Great to see that someone still uses this component and updates it to new polymer versions. Thanks!

I'll have a further look at the PR soon

**Comment by fxedel** [comment]
@RoXuS I still had to adjust a lot of things ... does the new version still work for you?

**Comment by GeoloeG-IsT** [comment]
@fxedel, can you merge it into master so I can test it?

**Comment by fxedel** [comment]
@MeTaNoV You can also git clone RoXuS/toggle-icon directly in your bower_components directory – I don't want to publish unconfirmed changes to the bower registry ;-)

**Comment by GeoloeG-IsT** [comment]
if I git clone, I won't get your PR...

**Comment by fxedel** [comment]
@MeTaNoV Of course you will. Just don't clone the [main repository fxedel/toggle-icon](https://github.com/fxedel/toggle-icon) but @RoXuS's [fork RoXuS/toggle-icon](https://github.com/RoXuS/toggle-icon).

So in your app workplace:
```
$ rm -r bower_components/toggle-icon
$ git clone git@github.com:RoXuS/toggle-icon.git bower_components/toggle-icon
```

**Comment by GeoloeG-IsT** [comment]
Already pointing to @RoXuS fork with my component, just missed the point that working on your side on this PR would update this fork version. It was already working for me, I'll take another look when I'll have time! ThX!

**Comment by GeoloeG-IsT** [comment]
@fxedel , I was able to test it again and found out that there is a remaining issue. When switching from check to uncheck or vice versa, only one icon is displayed. I didn't have time to investigate further. COuld you take a look at it? YOu can see a running version on the demo page of my component: https://www.webcomponents.org/element/GeoloeG/gold-password-input/demo/demo/index.html

**Comment by fxedel** [comment]
@MeTaNoV I can't reproduce this issue. Maybe I'll just merge this and you test it again.

**Comment by fxedel** [comment]
@MeTaNoV Your demo (which depends on toggle-icon#master – that can cause problems as it would also automatically use major updates (e.g. 1.2 -> 2.0) with breaking changes) still works the exact same way like before merging.

**Comment by GeoloeG-IsT** [comment]
I switched to your latest version and still have the same behavior. Your demo involving `checked` are also not working, At least when I am using Chrome 61.

**Comment by fxedel** [comment]
@MeTaNoV Ah, I tested it with Firefox. I can reproduce your issue in Chrome.

**Pull request merged**
